### PR TITLE
Max length warning instead of error

### PR DESCRIPTION
**Pull request by jamielob**

### CODE REVIEW

**Comment by jamielob** [comment]
Also added `no-param-reassign` relaxation rule.  Allows the assignment of new properties to an object which is a common pattern, especially in Meteor.

**Comment by pauldowman** [comment]
👍

**Comment by karldanninger** [comment]
I really want this <3 love you long time @jamielob

**Comment by cfnelson** [comment]
@jamielob I was going to ask if you could split the no-param-reassign to it's own PR. But I see its already been merged. 😂

**Pull request merged**
